export const EN_PALABRAS = [
  "¿Cuál es tu lugar preferido de tu casa? ¿por qué?",
  "¿Qué fantasía te gustaría bajar a la realidad?",
  "¿Qué actividad extrema te gustaría hacer?",
  "¿Cuáles son tus tres placeres culposos?",
  "¿Cuál era tu juego o juguete favorito de la infancia?",
  "¿Qué título le pondrías a una película sobre tu vida?",
  "¿Volver al pasado o ir al futuro? ¿por qué?",
  "Si pudieses crear un feriado, ¿por qué motivo sería?",
  "¿Con quién fue tu primer beso? ¿qué sentiste?",
  "Tres cosas que te gusta hacer y sentís que te salen mal.",
  "¿El último regalo que hiciste? ¿Y el último regalo que recibiste?",
  "Si fueses embajador, ¿qué lugar elegirías para irte a vivir? ¿A dónde no irías?",
  "¿En qué momento del día tenés tus mejores ideas?",
  "Si escribieras un libro, ¿de qué sería? ¿Cómo lo titularías?",
  "¿Qué es lo que más te gusta del barrio donde vivís?",
  "¿Qué tres deseos pedías cuando eras niño? ¿y ahora?",
  "Si fueses de otro género, ¿qué sería lo primero que harías?",
  "¿Un sueño recurrente?",
  "¿Una canción que te alegre?",
  "¿Qué recuerdo tenés de tu primera cita?",
  "Compartí un miedo absurdo que tengas.",
  "¿Quién de las personas presentes sería mejor comediante?",
  "¿Un pensamiento recurrente?",
  "¿Tu libro preferido?",
  "¿Qué es lo primero que miras en una persona?",
  "¿Qué personaje de película o serie te gustaría ser?",
  "¿Un viaje pendiente?",
  "Si algo te gusta, ¿asumirías cualquier riesgo?",
  "Si fueses un objeto, ¿cuál te gustaría ser?",
  "Tres cosas que te hacen sentir feliz.",
  "¿Te animarías a vivir una experiencia en el extranjero? ¿cuál?",
  "¿Tuviste alguna experiencia paranormal? ¿cómo fue y con quién/es estabas?",
  "Si fueses un animal, ¿cuál serías? ¿por qué?",
  "¿Tu película preferida?",
  "Un talento inútil que te dé orgullo es...",
  "¿Crees en el amor a primera vista?",
  "¿Sobre qué tema considerás que tienes mucho conocimiento?",
  "Si fueses una persona famosa, ¿quién serías? ¿por qué?",
  "¿Qué cuento te relataban en la infancia?",
  "¿Cuál es el mejor lugar que conociste?",
  "¿Qué canción elegirías para cantar en un karaoke?",
  "Tres cosas que te den vergüenza ajena.",
  "Si pudieras crear tu lugar en el mundo, ¿cómo sería?",
  "¿Una situación vergonzosa que recuerdes?",
  "¿Elegirías otra época para vivir? ¿cuál? ¿por qué?",
  "¿En qué te gustaría haber sido bueno?",
  "¿Algo ridículo por lo que te gustaría que te paguen?",
  "¿Te sentís libre de tomar tus propias decisiones?",
  "Si tuvieses que elegir una profesión, trabajo o carrera distinta, ¿cuál sería?",
  "¿Te define la opinión de los demás?",
  "Nombra tres características que te definan.",
  "¿De qué halago estás más orgulloso?",
  "¿Qué primera impresión crees que das?",
  "¿Qué actividades te divertían antes y ahora no?",
  "Cuando eras chico, ¿cómo te imaginabas siendo adulto?",
  "¿Sos idealista o realista? ¿Cómo impacta en tu vida y en tus relaciones?",
  "¿Una situación que te incomode?",
  "¿Un momento simple que disfrutes?",
  "¿Reconoces tus defectos? ¿y tus virtudes? ¿cuáles son?",
  "¿Te enamoraste alguna vez? ¿Quién fue la primera persona y qué te gustó de ella?",
  "¿Te gusta reflexionar solo o con otras personas? ¿Qué temas despiertan tu curiosidad últimamente?",
  "Quiero o tengo. ¿Cuál de las dos está más presente en tu cotidianidad?",
  "Si tuvieras que elegir una persona para que te acompañe en una experiencia espiritual, ¿quién sería? ¿por qué?",
  "¿Cuándo fue la última vez que hiciste algo por primera vez? ¿Qué fue?",
  "¿Qué actitudes no te gustan pero las toleras en una persona? ¿Cuál valoras?",
  "¿Qué disfrutas de tu cotidianidad? ¿y qué no?",
  "¿Hay alguna actividad que te guste tanto que te haga perder la noción del tiempo?",
  "La razón o la emoción. ¿Cuál de las dos tiene más peso en vos? ¿te gusta que sea así o preferirías que fuera al revés?",
  "¿Qué actividades tendes a dejar para después?",
  "¿Qué amas y la mayoría de la gente no?",
  "Perdonar o pedir perdón. ¿Cuál te cuesta más?",
  "¿Qué destacas de las personas que te criaron?",
  "¿Con qué tipo de personalidad solés conectar?",
  "Esta semana me puse contento por...",
  "¿Te asusta el futuro? ¿por qué?",
  "¿Cuál fue tu primera impresión de la persona que tenes a tu izquierda?",
  "¿Tomás decisiones porque te sentís preparado o porque son las esperadas para tu edad?",
  "¿Qué aventura tenes pendiente por realizar?",
  "¿Qué buscas en una pareja?",
  "¿Tenes alguna fuente de motivación hoy en día? ¿Cuál es o podría ser?",
  "¿Pensas más en el 'por qué' o en el 'para qué' de las cosas?",
  "¿Te permitís mostrarte vulnerable? ¿con quién?",
  "¿Una buena decisión?",
  "Si pudieses ser exitoso en lo que quieras, ¿en qué elegirías serlo?",
  "¿Qué destacas de tus amistades?",
  "¿Te dedicas tiempo a vos mismo? ¿qué haces en esos momentos?",
  "¿Solés culpar a otras personas por lo que te pasa? ¿en qué situaciones?",
  "¿Te considerás una persona prejuiciosa? ¿por qué?",
  "¿Una persona que te alivie en momentos tristes?",
  "¿Qué sensaciones tuviste en tu primer día de universidad/trabajo?",
  "Cuando te sentís bien con vos mismo, ¿con quién te gustaría estar?",
  "Los domingos son... ¿deprimentes o disfrutables? ¿te gusta arrancar la semana?",
  "Nombra a alguien que te inspire.",
  "¿Cómo reaccionas ante una actitud que te molesta?",
  "¿Qué momentos del día elegís para reflexionar?",
  "¿Crees que existe la amistad entre el hombre y la mujer?",
  "Cuando ayudas a alguien, ¿lo hacés por vos o por la otra persona?",
  "¿Elegimos lo que somos o nos lo impone nuestro entorno?",
  "¿Qué cambiarías del mundo?",
  "¿Qué pensas sobre la educación sin distinción de géneros?",
  "¿Qué cambiarías de tu crianza si tuvieras que educar a una persona?",
  "¿Qué rol cumplís en tu familia? ¿cómo te hace sentir?",
  "Pensá en alguien que te gustaría abrazar. ¿Quién es?",
  "¿Qué pensabas el día de tu casamiento? Si no te casaste, ¿te gustaría?",
  "¿Qué exigencias te ponés? ¿Haces algo para suavizarlas?",
  "¿Cuándo fue la última vez que lloraste? ¿por qué?",
];

export const DESCONECTADOS = [
  "Que amas y la matoria de la gente no?",
  "De que halago estas mas orgulloso?",
  "Una buena decision?",
  "Sos idealista o realista? Como impacta en tu vida y en tus relaciones?",
  "Que actividades te divertian antes y ahora no?",
  "Que sensaciones tuviste en tu primer dia de universidad/trabajo?. Si no fuiste, que pensas que sentirias?",
  "Reconoces tus defectos? Y tus virtudes? Cuales son?",
  "Soles culpar a otras personas por lo que te pasa? En que situaciones?",
  "Te gustra reflexionar solo o con otras personas? Que temas despiertan tu curiosidad ultimamente?",
  "Que actividad tendes a dejar para despues?",
  "Que momentos del dia elegis para reflexionar?",
  "Los domingos son... ¿deprimentes o disfrutables? ¿te gusta arrancar la semana?",
  "Que persona te alivia en momentos tristes?",
  "Hay alguna actividad que te guste tanto que te haga perder la nocion del tiempo?",
  "Tenes alguna fuente de motivacion hoy en dia? ¿Cual es o podria ser?",
  "Te dedicas tiempo a vos mismo? ¿que haces en esos momentos?",
  "Cual fue tu primera impresion de la persona que tenes a tu izquierda?",
  "Que primera impresion crees que das?",
  "Que destacas de las personas que te criaron?",
  "Que aventura tenes pendiente por realizar?",
  "Cuando fue la ultima vez que hiciste algo por primera vez? ¿Que fue?",
  "Que descatacas de tus amistades?",
  "Si puedeser exitoso en lo que quieras, ¿en que elegirias serlo?",
  "Un momento simple que disfrutes?",
  "Pensas mas en el 'por que' o en el 'para que' de las cosas?",
  "Te consideras una persona prejuiciosa? ¿Por que?",
  "Nombra tres caracteristicas que te definan.",
  "Nombra a alguien que te inspire.",
  "Perdonar o pedir perdon. ¿Cual te cuesta mas?",
  "Que actitudes no te gustan pero las toleras en una persona? ¿Cual valoras?",
  "Que disfrutas de tu cotidianidad? ¿Y que no?",
  "Una situacion que te incomode?",
  "Un talento inutil que te de orgullo es...",
  "Si fueses de otro genero, ¿que sería lo primero que harías?",
  "Que personaje de pelicula o serie te gustaria ser, ¿por que?",
  "Volver al pasado o ir al futuro? ¿Por que?",
  "Que fantasia te gustaria bajar a la realidad?",
  "Que actividad extrema te gustaria hacer?",
  "Tuviste alguna experiencia paranormal? ¿Como fue y con quien/es estabas?",
  "Algo ridículo por lo que te gustaría que te paguen?",
  "Elejirias otra epoca para vivir? ¿Cual? ¿Por que?",
  "El ultimo regalo que hiciste? ¿Y el ultimo regalo que recibiste?",
  "Te animarias a vivir una experiencia en el extranjero? ¿Cual?",
  "Tres cosas que te hacen sentir feliz.",
  "Una situacion vergonzosa que recuerdes?",
  "Película preferida?",
  "Tres cosas que te dan vergüenza ajena.",
  "Que titulo le pondrias a una pelicula sobre tu vida?",
  "Si fueses una persona famosa, ¿quien serias? ¿Por que?",
  "Si no te cela tu pareja, ¿te sientes menos querido?",
  "Crees en las segundas oportunidades?",
  "Que pensas de la monogamia?",
  "Como definis una relacion toxica?",
];

export const PICANTES = [
  "¿Qué es lo más atrevido que te gustaría probar en la cama?",
  "¿Alguna vez has tenido fantasías con alguien más mientras estabas conmigo?",
  "Si pudiéramos tener una noche sin límites, ¿qué te gustaría hacer?",
  "¿Cuál es tu lugar favorito para que te besen?",
  "¿Qué prenda de ropa crees que me haría ver más sexy?",
  "¿Te gustaría probar juguetes en la cama? ¿Cuál sería el primero?",
  "¿Prefieres hacerlo con luces encendidas o apagadas?",
  "¿Cuál es el lugar más inesperado donde te gustaría hacerlo?",
  "Si tuvieras que describir nuestra vida sexual en una palabra, ¿cuál sería?",
  "¿Qué es lo que más te excita de mí?",
  "¿Alguna vez has tenido un sueño erótico conmigo?",
  "¿Te gustaría grabarnos mientras lo hacemos?",
  "¿Qué parte de mi cuerpo te vuelve más loco/a?",
  "¿Te gustaría que probáramos nuevas posiciones? ¿Alguna en mente?",
  "¿Te gusta hablar sucio en la cama?",
  "¿Qué es lo más atrevido que has hecho sexualmente?",
  "Si tuvieras que elegir una fantasía para cumplir esta semana, ¿cuál sería?",
  "¿Te gustaría que usáramos disfraces para jugar en la cama?",
  "¿Prefieres ser dominante o sumiso/a?",
  "¿Cuál es el cumplido más sexy que te he dado?",
  "¿Te gustaría tener una sesión de masajes sensuales conmigo?",
  "¿Qué es lo que más te gusta que te haga en la cama?",
  "¿Alguna vez has usado aplicaciones o juguetes para mejorar tu vida sexual?",
  "¿Qué parte de mi cuerpo te gusta más tocar?",
  "Si pudieras tenerme en cualquier lugar ahora mismo, ¿dónde sería?",
  "¿Cuál es el cumplido más caliente que te gustaría escuchar de mí?",
  "¿Te gustaría experimentar con aceites o lociones en la cama?",
  "¿Qué palabra te enciende más cuando te la digo?",
  "¿Prefieres sesiones rápidas o largas y apasionadas?",
  "¿Qué es lo más inesperado que te ha excitado alguna vez?",
  "¿Cuál es tu fantasía sexual más secreta?",
  "¿Alguna vez has fingido un orgasmo? ¿Por qué?",
  "¿Te gusta usar ropa interior sexy? ¿Qué tipo prefieres?",
  "¿Has tenido algún sueño húmedo conmigo?",
  "¿Qué es lo más atrevido que has hecho en público?",
  "¿Te gustaría probar un trío alguna vez?",
  "¿Qué es lo primero que piensas cuando me ves desnudo/a?",
  "¿Te excita que te vean o te gusta mantenerlo privado?",
  "¿Te gustaría que te atara o me ataras a mí?",
  "¿Prefieres dominar o ser dominado/a en la cama?",
  "¿Qué parte de tu cuerpo crees que es la más sexy?",
  "¿Te gusta usar lencería o prefieres desnudez total?",
  "¿Qué posición crees que disfrutamos más juntos?",
  "¿Cuál ha sido el lugar más raro donde lo has hecho?",
  "¿Te gustaría experimentar con comida en la cama?",
  "¿Te excita la idea de hacerlo en un lugar público?",
  "¿Alguna vez te has grabado mientras lo hacías?",
  "¿Te gusta cuando te muerdo o prefieres caricias suaves?",
  "¿Cuál es la parte de mi cuerpo que más te excita?",
  "¿Te gustaría que usáramos vendas o esposas?",
  "¿Prefieres hacerlo lento y sensual o rápido y salvaje?",
  "¿Cuál es la fantasía más atrevida que has cumplido?",
  "¿Te gustaría probar juegos de rol? ¿Qué personaje serías?",
  "¿Te gusta hablar sucio o prefieres el silencio?",
  "¿Alguna vez te has sentido culpable después de tener sexo?",
  "¿Cuál es el cumplido más sexy que te he dado?",
  "¿Qué es lo primero que quisieras hacerme si estuviéramos solos ahora?",
  "¿Te excita la idea de hacerlo frente a un espejo?",
  "¿Te gusta que te besen el cuello o prefieres otras zonas?",
  "¿Alguna vez has tenido sexo en un coche?",
  "¿Qué tipo de ropa interior te gustaría que usara para sorprenderte?",
  "¿Qué es lo que más te gusta que te hagan en la cama?",
  "¿Te gustaría que probáramos posiciones nuevas cada semana?",
  "¿Te gustaría hacer un striptease para mí o que yo te lo haga?",
  "¿Has fantaseado alguna vez con alguien famoso?",
  "¿Te gusta probar cosas nuevas o prefieres lo clásico?",
  "¿Qué tipo de beso te excita más?",
  "¿Qué piensas cuando ves películas con escenas sexuales?",
  "¿Te gustaría hacerlo en el agua (ducha, piscina o mar)?",
  "¿Te excita la idea de que te sorprenda mientras te cambias?",
  "¿Qué palabra crees que describiría mejor nuestra vida sexual?",
  "¿Te gustaría jugar con hielo o cera caliente?",
  "¿Cuál ha sido el lugar más incómodo donde lo has hecho?",
  "¿Qué me pondrías para hacerme ver más sexy para ti?",
  "¿Te gustaría probar el sexo telefónico o sexting?",
  "¿Has fantaseado alguna vez con tener sexo frente a un espejo?",
  "¿Te gustaría sorprenderme con una noche temática de juegos en la cama?",
  "¿Qué tipo de música crees que es perfecta para el sexo?",
  "¿Qué tan aventurero/a crees que soy en la cama?",
  "¿Alguna vez has usado lubricantes con sabor o efectos especiales?",
  "¿Alguna vez chapaste en un colectivo o tren?",
  "¿Te garroneaste un trago en un boliche? ¿Cómo?",
  "¿Alguna vez te encaró alguien que no te acordabas haber conocido?",
  "Si tuvieras que elegir entre besar a un ex o a un amigo del grupo, ¿a quién elegís?",
  "¿Cuál es el lugar más raro donde tuviste un momento íntimo?",
  "¿Alguna vez te encaró alguien casado/a?",
  "¿A qué edad diste tu primer beso y cómo fue?",
  "¿Alguna vez te hiciste pasar por otra persona para levantar?",
  "¿Con quién del grupo te animarías a compartir cama después de una fiesta?",
  "¿Qué es lo más vergonzoso que te pasó en la playa?",
  "¿Preferís chapar con lengua o sin lengua?",
  "¿Alguna vez mandaste un mensaje hot al contacto equivocado?",
  "¿Te arrepentís de algún chamuyo que usaste?",
  "¿Alguna vez te hicieron una propuesta indecente? ¿La aceptaste?",
  "¿Qué es lo más bizarro que escuchaste en la cama?",
  "Si tuvieras que recrear una escena de película romántica, ¿cuál sería?",
  "¿Alguna vez te enamoraste de un profe o jefe?",
  "¿Preferís tener mucha química o mucha charla con alguien?",
  "¿Alguna vez te encontraron en una situación comprometedora?",
  "¿Con qué famoso argentino tendrías una cita si pudieras?",
];

export const DIVERTIDAS = [
  "¿Alguna vez chamuyaste con alguien solo para zafar de pagar algo?",
  "Si fueras un choripán, ¿con qué salsa te acompañarías?",
  "¿Qué harías si te cruzaras a Messi en el baño de un boliche?",
  "¿Cuál fue la peor cagada que te mandaste en un asado?",
  "¿Te tatuarías una frase de Ricardo Fort? ¿Cuál?",
  "¿Qué preferís: comer milanesa todos los días o nunca más comer una?",
  "Si tu vida fuera un meme, ¿cuál sería?",
  "¿Qué harías si te despertás en el Obelisco sin ropa?",
  "Si pudieras ser un personaje de Chiquititas o Cebollitas, ¿cuál serías?",
  "¿Cuál es el apodo más bizarro que te pusieron?",
  "¿Cuál fue tu peor papelón en un boliche?",
  "Si fueras un alfajor, ¿cuál serías?",
  "¿Te acordás de alguna excusa increíble que diste para zafar de algo?",
  "¿Qué es lo más random que llevaste en la mochila al colegio?",
  "¿Qué harías si quedás encerrado en un chino toda la noche?",
  "¿Preferís vivir sin mate o sin asado?",
  "¿Cuál es la peor mentira que le dijiste a tus viejos?",
  "¿Alguna vez mangueaste plata en la calle? ¿Por qué?",
  "Si pudieras elegir un poder, pero solo para usar en Argentina, ¿cuál sería?",
  "¿Qué harías si se te aparece el fantasma de Gilda en tu pieza?",
  "Si fueras un fernet, ¿cómo lo prepararías: puro o con coca al 70/30?",
  "¿Qué harías si te despertás en el medio de un partido de fútbol en la Bombonera?",
  "Si pudieras ser famoso por algo ridículo, ¿qué sería?",
  "¿Qué fue lo más vergonzoso que hiciste en una cita?",
  "Si fueras una empanada, ¿de qué sabor serías?",
  "¿Qué harías si te encontrás un billete falso en el vuelto del chino?",
  "¿Alguna vez mandaste un mensaje criticando a alguien y se lo enviaste a esa persona?",
  "¿Qué preferís: vivir sin memes o sin redes sociales?",
  "Si tu vida fuera una cumbia, ¿cuál sería el nombre del tema?",
  "¿Cuál fue el chamuyo más ridículo que te tiraron y funcionó?",
  "¿Qué es lo más loco que harías por un millón de pesos?",
  "¿Qué harías si mañana fueras presidente por un día?",
  "Si pudieras elegir un talento inútil para ser el mejor, ¿cuál sería?",
  "¿Alguna vez mentiste para zafar de una multa?",
  "¿Qué harías si te despertás con una foto tuya viral en Twitter?",
  "Si fueras parte de un reality show argentino, ¿cuál elegirías?",
  "¿Qué preferís: nunca más tomar mate o nunca más tomar birra?",
  "¿Cuál fue la peor mentira que dijiste para evitar un compromiso?",
  "Si te dieran un micrófono en la cancha, ¿qué gritarías?",
  "Si tuvieras que vivir en una película argentina, ¿cuál sería?",
  "¿Qué personaje de Los Simuladores serías y por qué?",
  "¿Preferís vivir sin internet o sin televisión para siempre?",
  "Si tuvieras que usar la camiseta de tu equipo rival, ¿qué excusa pondrías?",
  "¿Qué harías si te despertaras con el look de Ricardo Fort?",
  "Si pudieras salir en un meme viral, ¿cómo te gustaría que fuera?",
]

export const VERDADOMENTIRA = [
  "¿Alguna vez te colaste en un recital o partido de fútbol?",
  "¿Te fuiste sin pagar de algún lado?",
  "¿Te hiciste pasar por extranjero para no hablar con alguien?",
  "¿Alguna vez te levantaste a alguien usando una frase muy grasa?",
  "¿Es verdad que alguna vez usaste una excusa médica falsa para faltar al trabajo?",
  "¿Alguna vez te hiciste el dormido/a para no saludar a alguien en la calle?",
  "¿Mentiste sobre tus gustos musicales para encajar en un grupo?",
  "¿Alguna vez te comiste la comida de otra persona en la heladera y nunca lo confesaste?",
  "¿Usaste alguna vez la excusa “no tengo señal” para no responder mensajes?",
  "¿Alguna vez le mentiste a tu pareja sobre dónde estabas?",
  "¿Alguna vez lloraste viendo una novela o película argentina?",
  "¿Te escapaste de tu casa sin permiso cuando eras chico?",
  "¿Alguna vez le robaste algo a un amigo o familiar?",
  "¿Es verdad que alguna vez inventaste una excusa para no devolver algo prestado?",
  "¿Alguna vez te quedaste con el vuelto de más y no dijiste nada?",
  "¿Alguna vez hiciste trampa en un juego de mesa y no lo admitiste?",
  "¿Te fuiste alguna vez de un boliche sin pagar la entrada?",
  "¿Alguna vez saliste con alguien solo por conveniencia?",
  "¿Es verdad que alguna vez stalkeaste a alguien durante horas?",
  "¿Alguna vez te hiciste el borracho para evitar una conversación incómoda?",
  "¿Le mentiste a un profesor para zafar de un examen o entrega?",
  "¿Alguna vez fingiste estar enfermo para no ir al trabajo o a la escuela?",
  "¿Alguna vez fingiste no conocer a alguien para evitar saludarlo?",
  "¿Es verdad que alguna vez robaste Wi-Fi del vecino?",
  "¿Alguna vez te hiciste pasar por otra persona en redes sociales?",
  "¿Te reíste alguna vez de algo que no entendiste solo para quedar bien?",
  "¿Es verdad que alguna vez borraste mensajes antes de que alguien los leyera?",
  "¿Alguna vez te fuiste de un restaurante sin pagar?",
  "¿Es verdad que alguna vez hiciste captura de pantalla a un chat para mandarlo a otro?",
  "¿Alguna vez te colaste en un evento o recital sin entrada?",
  "¿Es verdad que alguna vez volviste con un ex y no lo contaste?",
  "¿Alguna vez fingiste no escuchar algo para evitar un conflicto?",
  "¿Le mentiste a alguien sobre tu nombre para no dar explicaciones?",
  "¿Es verdad que alguna vez dijiste que estabas en casa pero estabas en otro lado?",
  "¿Alguna vez bloqueaste a alguien y después lo desbloqueaste para ver qué hacía?",
  "¿Te arrepentiste alguna vez de un beso pero nunca lo confesaste?",
  "¿Alguna vez dijiste estar de novio/a solo para evitar que alguien te encare?",
  "¿Es verdad que alguna vez dijiste 'ya estoy llegando' y estabas en tu casa?",
  "¿Alguna vez inventaste una historia para dar lástima y conseguir algo?"
]