export const EN_PALABRAS = [
  { question: "¿Cuál es tu lugar preferido de tu casa? ¿por qué?", category: "Personal" },
  { question: "¿Qué fantasía te gustaría bajar a la realidad?", category: "Imaginación" },
  { question: "¿Qué actividad extrema te gustaría hacer?", category: "Aventuras" },
  { question: "¿Cuáles son tus tres placeres culposos?", category: "Personal" },
  { question: "¿Cuál era tu juego o juguete favorito de la infancia?", category: "Infancia" },
  { question: "¿Qué título le pondrías a una película sobre tu vida?", category: "Creatividad" },
  { question: "¿Volver al pasado o ir al futuro? ¿por qué?", category: "Reflexión" },
  { question: "Si pudieses crear un feriado, ¿por qué motivo sería?", category: "Creatividad" },
  { question: "¿Con quién fue tu primer beso? ¿qué sentiste?", category: "Relaciones" },
  { question: "Tres cosas que te gusta hacer y sentís que te salen mal.", category: "Personal" },
  { question: "¿El último regalo que hiciste? ¿Y el último regalo que recibiste?", category: "Relaciones" },
  { question: "Si fueses embajador, ¿qué lugar elegirías para irte a vivir? ¿A dónde no irías?", category: "Viajes" },
  { question: "¿En qué momento del día tenés tus mejores ideas?", category: "Reflexión" },
  { question: "Si escribieras un libro, ¿de qué sería? ¿Cómo lo titularías?", category: "Creatividad" },
  { question: "¿Qué es lo que más te gusta del barrio donde vivís?", category: "Personal" },
  { question: "¿Qué tres deseos pedías cuando eras niño? ¿y ahora?", category: "Sueños" },
  { question: "Si fueses de otro género, ¿qué sería lo primero que harías?", category: "Imaginación" },
  { question: "¿Un sueño recurrente?", category: "Sueños" },
  { question: "¿Una canción que te alegre?", category: "Música" },
  { question: "¿Qué recuerdo tenés de tu primera cita?", category: "Relaciones" },
  { question: "Compartí un miedo absurdo que tengas.", category: "Personal" },
  { question: "¿Quién de las personas presentes sería mejor comediante?", category: "Social" },
  { question: "¿Un pensamiento recurrente?", category: "Reflexión" },
  { question: "¿Tu libro preferido?", category: "Lectura" },
  { question: "¿Qué es lo primero que miras en una persona?", category: "Relaciones" },
  { question: "¿Qué personaje de película o serie te gustaría ser?", category: "Imaginación" },
  { question: "¿Un viaje pendiente?", category: "Viajes" },
  { question: "Si algo te gusta, ¿asumirías cualquier riesgo?", category: "Valores" },
  { question: "Si fueses un objeto, ¿cuál te gustaría ser?", category: "Imaginación" },
  { question: "Tres cosas que te hacen sentir feliz.", category: "Personal" },
  { question: "¿Te animarías a vivir una experiencia en el extranjero? ¿cuál?", category: "Viajes" },
  { question: "¿Tuviste alguna experiencia paranormal? ¿cómo fue y con quién/es estabas?", category: "Experiencias" },
  { question: "Si fueses un animal, ¿cuál serías? ¿por qué?", category: "Imaginación" },
  { question: "¿Tu película preferida?", category: "Cine" },
  { question: "Un talento inútil que te dé orgullo es...", category: "Personal" },
  { question: "¿Crees en el amor a primera vista?", category: "Relaciones" },
  { question: "¿Sobre qué tema considerás que tienes mucho conocimiento?", category: "Conocimiento" },
  { question: "Si fueses una persona famosa, ¿quién serías? ¿por qué?", category: "Imaginación" },
  { question: "¿Qué cuento te relataban en la infancia?", category: "Infancia" },
  { question: "¿Cuál es el mejor lugar que conociste?", category: "Viajes" },
  { question: "¿Qué canción elegirías para cantar en un karaoke?", category: "Música" },
  { question: "Tres cosas que te den vergüenza ajena.", category: "Personal" },
  { question: "Si pudieras crear tu lugar en el mundo, ¿cómo sería?", category: "Creatividad" },
  { question: "¿Una situación vergonzosa que recuerdes?", category: "Experiencias" },
  { question: "¿Elegirías otra época para vivir? ¿cuál? ¿por qué?", category: "Imaginación" },
  { question: "¿En qué te gustaría haber sido bueno?", category: "Reflexión" },
  { question: "¿Algo ridículo por lo que te gustaría que te paguen?", category: "Creatividad" },
  { question: "¿Te sentís libre de tomar tus propias decisiones?", category: "Valores" },
  { question: "Si tuvieses que elegir una profesión, trabajo o carrera distinta, ¿cuál sería?", category: "Reflexión" },
  { question: "¿Te define la opinión de los demás?", category: "Reflexión" },
  { question: "Nombra tres características que te definan.", category: "Personal" },
  { question: "¿De qué halago estás más orgulloso?", category: "Personal" },
  { question: "¿Qué primera impresión crees que das?", category: "Social" },
  { question: "¿Qué actividades te divertían antes y ahora no?", category: "Reflexión" },
  { question: "Cuando eras chico, ¿cómo te imaginabas siendo adulto?", category: "Infancia" },
];


export const DESCONECTADOS = [
  { question: "Que amas y la mayoría de la gente no?", category: "Personal" },
  { question: "De qué halago estás más orgulloso?", category: "Personal" },
  { question: "Una buena decisión?", category: "Reflexión" },
  { question: "¿Sos idealista o realista? ¿Cómo impacta en tu vida y en tus relaciones?", category: "Reflexión" },
  { question: "¿Qué actividades te divertían antes y ahora no?", category: "Reflexión" },
  { question: "¿Qué sensaciones tuviste en tu primer día de universidad/trabajo? Si no fuiste, ¿qué pensas que sentirías?", category: "Experiencias" },
  { question: "¿Reconoces tus defectos? ¿Y tus virtudes? ¿Cuáles son?", category: "Personal" },
  { question: "¿Soles culpar a otras personas por lo que te pasa? ¿En qué situaciones?", category: "Reflexión" },
  { question: "¿Te gusta reflexionar solo o con otras personas? ¿Qué temas despiertan tu curiosidad últimamente?", category: "Reflexión" },
  { question: "¿Qué actividad tendes a dejar para después?", category: "Reflexión" },
  { question: "¿Qué momentos del día elegís para reflexionar?", category: "Reflexión" },
  { question: "Los domingos son... ¿deprimentes o disfrutables? ¿Te gusta arrancar la semana?", category: "Rutina" },
  { question: "¿Qué persona te alivia en momentos tristes?", category: "Relaciones" },
  { question: "¿Hay alguna actividad que te guste tanto que te haga perder la noción del tiempo?", category: "Intereses" },
  { question: "¿Tenés alguna fuente de motivación hoy en día? ¿Cuál es o podría ser?", category: "Motivación" },
  { question: "¿Te dedicás tiempo a vos mismo? ¿Qué hacés en esos momentos?", category: "Cuidado Personal" },
  { question: "¿Cuál fue tu primera impresión de la persona que tenés a tu izquierda?", category: "Social" },
  { question: "¿Qué primera impresión crees que das?", category: "Social" },
  { question: "¿Qué destacás de las personas que te criaron?", category: "Relaciones" },
  { question: "¿Qué aventura tenés pendiente por realizar?", category: "Aventuras" },
  { question: "¿Cuándo fue la última vez que hiciste algo por primera vez? ¿Qué fue?", category: "Experiencias" },
  { question: "¿Qué destacás de tus amistades?", category: "Relaciones" },
  { question: "Si pudieses ser exitoso en lo que quieras, ¿en qué elegirías serlo?", category: "Sueños" },
  { question: "¿Un momento simple que disfrutes?", category: "Rutina" },
  { question: "¿Pensás más en el 'por qué' o en el 'para qué' de las cosas?", category: "Reflexión" },
  { question: "¿Te considerás una persona prejuiciosa? ¿Por qué?", category: "Reflexión" },
  { question: "Nombra tres características que te definan.", category: "Personal" },
  { question: "Nombra a alguien que te inspire.", category: "Inspiración" },
  { question: "Perdonar o pedir perdón. ¿Cuál te cuesta más?", category: "Reflexión" },
  { question: "¿Qué actitudes no te gustan pero las tolerás en una persona? ¿Cuál valorás?", category: "Relaciones" },
  { question: "¿Qué disfrutás de tu cotidianidad? ¿Y qué no?", category: "Rutina" },
  { question: "¿Una situación que te incomode?", category: "Experiencias" },
  { question: "Un talento inútil que te dé orgullo es...", category: "Personal" },
  { question: "Si fueses de otro género, ¿qué sería lo primero que harías?", category: "Imaginación" },
  { question: "¿Qué personaje de película o serie te gustaría ser? ¿Por qué?", category: "Imaginación" },
  { question: "¿Volver al pasado o ir al futuro? ¿Por qué?", category: "Reflexión" },
  { question: "¿Qué fantasía te gustaría bajar a la realidad?", category: "Sueños" },
  { question: "¿Qué actividad extrema te gustaría hacer?", category: "Aventuras" },
  { question: "¿Tuviste alguna experiencia paranormal? ¿Cómo fue y con quién/es estabas?", category: "Experiencias" },
  { question: "¿Algo ridículo por lo que te gustaría que te paguen?", category: "Creatividad" },
  { question: "¿Elegirías otra época para vivir? ¿Cuál? ¿Por qué?", category: "Imaginación" },
  { question: "¿El último regalo que hiciste? ¿Y el último regalo que recibiste?", category: "Relaciones" },
  { question: "¿Te animarías a vivir una experiencia en el extranjero? ¿Cuál?", category: "Viajes" },
  { question: "Tres cosas que te hacen sentir feliz.", category: "Personal" },
  { question: "¿Una situación vergonzosa que recuerdes?", category: "Experiencias" },
  { question: "¿Película preferida?", category: "Cine" },
  { question: "Tres cosas que te dan vergüenza ajena.", category: "Personal" },
  { question: "¿Qué título le pondrías a una película sobre tu vida?", category: "Creatividad" },
  { question: "Si fueses una persona famosa, ¿quién serías? ¿Por qué?", category: "Imaginación" },
  { question: "Si no te cela tu pareja, ¿te sientes menos querido?", category: "Relaciones" },
  { question: "¿Crees en las segundas oportunidades?", category: "Relaciones" },
  { question: "¿Qué pensás de la monogamia?", category: "Relaciones" },
  { question: "¿Cómo definís una relación tóxica?", category: "Relaciones" },
];

export const PICANTES = [
  { question: "¿Qué es lo más atrevido que te gustaría probar en la cama?", category: "Intimidad" },
  { question: "¿Alguna vez has tenido fantasías con alguien más mientras estabas conmigo?", category: "Confesiones" },
  { question: "Si pudiéramos tener una noche sin límites, ¿qué te gustaría hacer?", category: "Intimidad" },
  { question: "¿Cuál es tu lugar favorito para que te besen?", category: "Intimidad" },
  { question: "¿Qué prenda de ropa crees que me haría ver más sexy?", category: "Intimidad" },
  { question: "¿Te gustaría probar juguetes en la cama? ¿Cuál sería el primero?", category: "Intimidad" },
  { question: "¿Prefieres hacerlo con luces encendidas o apagadas?", category: "Preferencias" },
  { question: "¿Cuál es el lugar más inesperado donde te gustaría hacerlo?", category: "Aventuras" },
  { question: "Si tuvieras que describir nuestra vida sexual en una palabra, ¿cuál sería?", category: "Confesiones" },
  { question: "¿Qué es lo que más te excita de mí?", category: "Intimidad" },
  { question: "¿Alguna vez has tenido un sueño erótico conmigo?", category: "Confesiones" },
  { question: "¿Te gustaría grabarnos mientras lo hacemos?", category: "Intimidad" },
  { question: "¿Qué parte de mi cuerpo te vuelve más loco/a?", category: "Intimidad" },
  { question: "¿Te gustaría que probáramos nuevas posiciones? ¿Alguna en mente?", category: "Preferencias" },
  { question: "¿Te gusta hablar sucio en la cama?", category: "Preferencias" },
  { question: "¿Qué es lo más atrevido que has hecho sexualmente?", category: "Experiencias" },
  { question: "Si tuvieras que elegir una fantasía para cumplir esta semana, ¿cuál sería?", category: "Fantasías" },
  { question: "¿Te gustaría que usáramos disfraces para jugar en la cama?", category: "Fantasías" },
  { question: "¿Prefieres ser dominante o sumiso/a?", category: "Preferencias" },
  { question: "¿Cuál es el cumplido más sexy que te he dado?", category: "Confesiones" },
];

export const DIVERTIDAS = [
  { question: "¿Alguna vez chamuyaste con alguien solo para zafar de pagar algo?", category: "Historias" },
  { question: "Si fueras un choripán, ¿con qué salsa te acompañarías?", category: "Creatividad" },
  { question: "¿Qué harías si te cruzaras a Messi en el baño de un boliche?", category: "Hipotéticos" },
  { question: "¿Cuál fue la peor cagada que te mandaste en un asado?", category: "Historias" },
  { question: "¿Te tatuarías una frase de Ricardo Fort? ¿Cuál?", category: "Humor" },
  { question: "¿Qué preferís: comer milanesa todos los días o nunca más comer una?", category: "Decisiones" },
  { question: "Si tu vida fuera un meme, ¿cuál sería?", category: "Creatividad" },
  { question: "¿Qué harías si te despertás en el Obelisco sin ropa?", category: "Hipotéticos" },
  { question: "Si fueras un alfajor, ¿cuál serías?", category: "Creatividad" },
  { question: "¿Cuál fue tu peor papelón en un boliche?", category: "Historias" },
];

export const VERDADOMENTIRA = [
  { question: "¿Alguna vez te colaste en un recital o partido de fútbol?", category: "Experiencias" },
  { question: "¿Te fuiste sin pagar de algún lado?", category: "Confesiones" },
  { question: "¿Te hiciste pasar por extranjero para no hablar con alguien?", category: "Mentiras" },
  { question: "¿Alguna vez usaste una excusa médica falsa para faltar al trabajo?", category: "Confesiones" },
  { question: "¿Alguna vez fingiste estar enfermo para no ir al trabajo o a la escuela?", category: "Mentiras" },
  { question: "¿Alguna vez dijiste estar de novio/a solo para evitar que alguien te encare?", category: "Confesiones" },
  { question: "¿Alguna vez fingiste no conocer a alguien para evitar saludarlo?", category: "Mentiras" },
  { question: "¿Alguna vez bloqueaste a alguien y después lo desbloqueaste para ver qué hacía?", category: "Confesiones" },
  { question: "¿Es verdad que alguna vez volviste con un ex y no lo contaste?", category: "Confesiones" },
  { question: "¿Alguna vez inventaste una historia para dar lástima y conseguir algo?", category: "Mentiras" },
];